"""agregamos nueva columna a los items a traves de clase heredada

Revision ID: 0336c7b7e992
Revises: 11ab58c4cdf1
Create Date: 2026-03-04 10:02:10.017187

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0336c7b7e992'
down_revision = '11ab58c4cdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
