"""agregamos la tabla libros

Revision ID: 3e775bab490a
Revises: fb8a49357d21
Create Date: 2026-03-10 09:50:31.932132

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3e775bab490a'
down_revision = 'fb8a49357d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libro',
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('autor', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('editorial', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creador_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('producto', sa.Column('tamano', sa.Float(), nullable=False))
    op.add_column('producto', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'created_at')
    op.drop_column('producto', 'tamano')
    op.drop_table('libro')
    # ### end Alembic commands ###
