"""restingido el isbn a solo numeros

Revision ID: 6d56ef4aaf7c
Revises: d75e512004e6
Create Date: 2026-03-10 11:50:14.607480

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d56ef4aaf7c'
down_revision = 'd75e512004e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_libro_isbn_numeric",
        "libro",
        "isbn ~ '^[0-9]{10,13}$'",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_libro_isbn_numeric", "libro", type_="check")
    # ### end Alembic commands ###
