"""actualizamos tabla libros

Revision ID: d75e512004e6
Revises: 3e775bab490a
Create Date: 2026-03-10 10:18:19.897046

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd75e512004e6'
down_revision = '3e775bab490a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('libro', 'isbn',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('libro', 'isbn',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=13),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
